#!/bin/sh


# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0
rm -f *.obj *.dat
rm -rf ZZ_python *.png

# ----------------------------------------------------------------- end-of-file
