#!/bin/bash
# Name of the job
#SBATCH -J pipe-medium-hfdibrans
# Partition to use
#SBATCH -p express
# Time limit. Often not needed as there are defaults,
#SBATCH -t 6:00:00
# Nodelist
##SBATCH -x kraken-l[1-4]
# Number of processes
#SBATCH -n 1
#SBATCH -N 1

# source openfoam run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# copy mesh
cp -r ../mesh/hfdibrans/constant/polyMesh constant/polyMesh

# copy IC
mkdir -p 0
cp -rf 0.org/* 0

# generate lambda field
runApplication createLambdaBoundary

# create new patch from boundary faces inside lambda
runApplication createPatch -overwrite -dict system/createPatchDictNewPatch

# correct the lambda field based on the new boundary
python3 rewriteLambdaBoundary.py
runApplication correctLambdaBoundary

# create files for postprocessing
paraFoam -touch

# get the solver application
application=`getApplication`

# run the application
runApplication $application

# postprocessing
runApplication readAndWriteVelocity
runApplication readAndWriteTurbulenceFields omega
runApplication readAndWriteHFDIBSigma
